# Generated by Django 5.2a1 on 2025-03-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('leader', 'Тимлид'), ('member', 'Участник')], default='member', max_length=10),
        ),
    ]
