# Generated by Django 5.2a1 on 2025-03-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Тимлид'),
        ),
    ]
